# Generated by Django 4.2.8 on 2023-12-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=255, unique=True)),
                ('carrier', models.CharField(max_length=255)),
                ('sender_address', models.CharField(max_length=255)),
                ('receiver_address', models.CharField(max_length=255)),
                ('article_name', models.CharField(max_length=255)),
                ('article_quantity', models.IntegerField()),
                ('article_price', models.FloatField()),
                ('sku', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('IT', 'in-transit'), ('IN', 'inbound-scan'), ('DL', 'delivery'), ('TR', 'transit'), ('SC', 'scanned')], default='IT', max_length=2)),
            ],
        ),
    ]
