# Generated by Django 4.2.8 on 2023-12-31 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_weathermodel_rename_shipment_shipmentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathermodel',
            name='description',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='weathermodel',
            name='temprature',
            field=models.FloatField(null=True),
        ),
    ]
